[package]
name = "BadOS-Shell-System"
version = "0.1.0-dev"
authors = ["Logan Dhillon <ldmdev64@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"