name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install toolchain 'nightly-x86_64-unknown-linux-gnu'
      run: rustup toolchain install nightly-x86_64-unknown-linux-gnu

    - name: Add rust-src component
      run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
      
    - uses: actions/checkout@v3
    
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
